spring:
  data:
    mongodb:
      uri: mongodb+srv://user:dsdPassword@cluster0.e1yles2.mongodb.net/?retryWrites=true&w=majority
      database: dsd
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 690055730596-6vipmahvt87vqf4j8dqc8gpotfa0r3eb.apps.googleusercontent.com
            client-secret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  profiles:
    active: local